name: Update README with Tree

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install tree
        run: sudo apt-get install -y tree

      - name: Generate tree and update README
        run: |
          echo '```' >> tree_section
          tree -L 1 -d >> tree_section
          echo '```' >> tree_section

          awk '
            /<!-- tree-start -->/{
              print
              while(getline line < "tree_section" ) print line
              next
            }
            /<!-- tree-end -->/{
              print
              next
            }
            { print }
          ' README.md > README.tmp

          mv README.tmp README.md
          rm tree_section

      - name: Commit and push if changed
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git diff --quiet || (git add README.md && git commit -m "Update tree in README" && git push)
